### ISSUE TITLE
OSX make error

### ISSUE THREAD

**Issue by dmolony** [dschmenk/PLASMA#15]
After following the instructions I get:

MBP3:~/plasma/src/PLASMA/src $ make
cc    -c -o toolsrc/parse.o toolsrc/parse.c
cc    -c -o toolsrc/lex.o toolsrc/lex.c
cc    -c -o toolsrc/codegen.o toolsrc/codegen.c
toolsrc/codegen.c:470:24: error: use of undeclared identifier 'uintptr_t'
        str = (char *)(uintptr_t)constval;
                       ^
1 error generated.
make: *** [toolsrc/codegen.o] Error 1

**Comment by peterferrie** [comment]
> After following the instructions I get:
>
> MBP3:~/plasma/src/PLASMA/src $ make
> cc    -c -o toolsrc/parse.o toolsrc/parse.c
> cc    -c -o toolsrc/lex.o toolsrc/lex.c
> cc    -c -o toolsrc/codegen.o toolsrc/codegen.c
> toolsrc/codegen.c:470:24: error: use of undeclared identifier 'uintptr_t'
>         str = (char *)(uintptr_t)constval;
>                        ^
> 1 error generated.
> make: *** [toolsrc/codegen.o] Error 1

What version of the compiler are you using?
uintptr_t is very important to compile correctly on 64-bit platforms.
I suppose that we can typedef it into something if it doesn't exist...

**Comment by dmolony** [comment]
Hi Peter

It's a standard Sierra mac (without homebrew at the moment)

MBP3:~/plasma/src/PLASMA/src $ cc --version
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

Does that help?

Denis

**Comment by dschmenk** [comment]
I'm unclear as to what uintptr_t is supposed to improve.

**Comment by lifepillar** [comment]
@dmolony `brew install lifepillar/appleii/plasma` uses the latest revision that builds correctly in macOS Sierra (a5215e330905e8ecc026dcddcb5afb24b54f4efa), so you may use that for now. Note that `brew install lifepillar/appleii/plasma --HEAD` builds the current master instead, so at this time that is broken because of this issue.

**Comment by peterferrie** [comment]
> I'm unclear as to what uintptr_t is supposed to improve.

uintptr_t is an unsigned int that is capable of storing a pointer.
The code is casting from a long to a pointer, which can result in data
loss on some platforms.  The cast is used to convert the value safely.

**Comment by peterferrie** [comment]
Hi Denis,

> It's a standard Sierra mac (without homebrew at the moment)
>
> MBP3:~/plasma/src/PLASMA/src $ cc --version
> Apple LLVM version 8.0.0 (clang-800.0.42.1)
> Target: x86_64-apple-darwin16.3.0
> Thread model: posix
> InstalledDir:
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
>
> Does that help?

Yes, please sync and try again.  I've added a reference to the header
file where it should be defined for your system.

**Comment by dschmenk** [comment]
>  I'm unclear as to what uintptr_t is supposed to improve.
uintptr_t is an unsigned int that is capable of storing a pointer.
The code is casting from a long to a pointer, which can result in data
loss on some platforms.  The cast is used to convert the value safely.

Except that the original value is a long, so by casting through an intermediate uintptr_t to something like a (char *) is just being pedantic. The proper way to fix is to make the original value a uintptr_t instead of a long so as to not lose precision.

**Comment by dmolony** [comment]
Hi

I deleted the PLASMA folder and did the clone step again. The result of 'make' is:



Regards

Denis

**Comment by dschmenk** [comment]
Peter, are you going to fix these nonsense casts:

        str = (char *)(uintptr_t)constval;

**Comment by peterferrie** [comment]
Peter, are you going to fix these nonsense casts:

    str = (char *)(uintptr_t)constval;


Yes, when I have time. If you get to it first, then go ahead.
