### ISSUE TITLE
apple2 europlus (1982)

### ISSUE THREAD

**Issue by counilh** [dschmenk/PLASMA#61]
Hi,
I'm trying to revive an apple II europlus that I bought in 1982 (the equivalent of 2 months salary !) and with which I learned programming and computers. I have some problems re-reading the old floppy disks (a master dos 3.3 ok - also locksmith4.0 - but no game and no floppy under cp / m is readable).
I would like to use your protocol to dialogue with him and show my sons that there is something other than Fortnite in life ... However, in the 2020 photo I do not understand all the wiring (https://user-images.githubusercontent.com/5579123/79223990-577fb400-7e28-11ea-9ac6-105dfd441894.jpg) compared to previous photos (2016 )
http://schmenk.is-a-geek.com/wordpress/wp-content/uploads/2016/08/IMG_2321-225x300.jpg 
http://schmenk.is-a-geek.com/wordpress/wp-content/uploads/2016/08/IMG_2335-225x300.jpg
If I understand correctly there are 4 pins (3,6,7,8) on the arduino which go respectively to the ports (14,5,2,15) of the game port of apple2. Why on the photo of april 2020 there are 2 rows of the plate ribbon that go to the apple game port. Moreover you use (GND and 5V arduino). Are they okay on 1 and 8 of the game port? Can you enlighten me.
For the rest I am under unbuntu 16.04 lts and I am having fun with raspi and arduino. I managed to install and compile the examples with PLASMA. Also I expect a lot from your help. 
Thanks in advance
Regards

**Comment by dschmenk** [comment]
Hi there-

You can see the pins used for the game port on my website: http://schmenk.is-a-geek.com/wordpress/?p=239

Follow the links to for the game port diagram to make sure you connect the correct pins.

I’m not sure where you found the picture from 2020, but it looks like they used a breadboard to build a temporary setup. It may have made it easier to debug, as well.

You will need to get floppy images onto real floppy disks in order to run the PLASMA programs on the Apple II: https://github.com/dschmenk/PLASMA/tree/master/images/apple <https://github.com/dschmenk/PLASMA/tree/master/images/apple>

Good luck
